[tool.isort]
add_imports = [
    "from __future__ import annotations",
]
force_single_line = true
profile = "black"

[tool.ruff]
line-length = 79

[tool.ruff.format]
quote-style = "single"

[tool.coverage.run]
plugins = ["covdefaults"]

[tool.coverage.report]
fail_under = 1
